version: 2

sources:
  - name: silver
    description: "Dữ liệu đã được làm sạch và chuẩn hóa từ layer Silver"
    database: lakehouse
    schema: silver
    tables:
      - name: stg_categories
        description: "Dữ liệu danh mục sản phẩm đã được chuẩn hóa"
      - name: stg_clickstream
        description: "Dữ liệu luồng nhấp chuột của người dùng"
      - name: stg_customers
        description: "Dữ liệu khách hàng đã được chuẩn hóa"
      - name: stg_order_items
        description: "Dữ liệu chi tiết đơn hàng đã được chuẩn hóa"
      - name: stg_orders
        description: "Dữ liệu đơn hàng đã được chuẩn hóa"
      - name: stg_products
        description: "Dữ liệu sản phẩm đã được chuẩn hóa"
      - name: stg_shipping
        description: "Dữ liệu vận chuyển đã được chuẩn hóa"
      - name: stg_stores
        description: "Dữ liệu cửa hàng đã được chuẩn hóa"
  - name: gold
    description: "Dữ liệu đã được xử lý và tối ưu hóa từ layer Gold"
    schema: gold
    tables:
      - name: dim_audit
        description: "Bảng kiểm tra dữ liệu"
      - name: dim_category
        description: "Bảng chiều danh mục sản phẩm"
      - name: dim_customer
        description: "Bảng chiều thông tin khách hàng"
      - name: dim_date
        description: "Bảng chiều thời gian"
      - name: dim_delivery_status
        description: "Bảng chiều trạng thái giao hàng"
      - name: dim_geography
        description: "Bảng chiều địa lý"
      - name: dim_order_status
        description: "Bảng chiều trạng thái đơn hàng"
      - name: dim_payment_type
        description: "Bảng chiều loại thanh toán"
      - name: dim_product
        description: "Bảng chiều sản phẩm"
      - name: dim_shipping_mode
        description: "Bảng chiều phương thức vận chuyển"
      - name: dim_store
        description: "Bảng chiều cửa hàng"
      - name: fact_sales
        description: "Bảng sự kiện doanh số bán hàng"