#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default system properties included when running spark-submit.
# This is useful for setting default environmental settings.



# Spark Configuration
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.driver.memory=4g
spark.executor.memory=4g
spark.executor.cores=2
spark.memory.fraction=0.75
spark.memory.storageFraction=0.3
spark.sql.shuffle.partitions=4
# spark.sql.iceberg.vectorization.enabled=false

# ICEBER config
spark.sql.iceberg.handle-timestamp-without-timezone=true

# Set Nessie as default catalog
spark.sql.defaultCatalog=lakehouse

# Nessie Catalog Configuration
spark.sql.catalog.lakehouse=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lakehouse.catalog-impl=org.apache.iceberg.rest.RESTCatalog
spark.sql.catalog.lakehouse.io-impl=org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.lakehouse.warehouse=s3://lakehouse/
spark.sql.catalog.lakehouse.uri=http://rest:8181
spark.sql.catalog.lakehouse.s3.endpoint=http://minio:9000
spark.sql.catalog.lakehouse.s3.path-style-access=true
spark.sql.catalog.lakehouse.s3.access-key-id=admin
spark.sql.catalog.lakehouse.s3.secret-access-key=admin123
spark.sql.catalog.lakehouse.s3.default-options.region=us-east-1

# AWS config
spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.access.key=admin
spark.hadoop.fs.s3a.secret.key=admin123
spark.hadoop.fs.s3a.default-options.region=us-east-1